name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build projects
      run: cargo build --verbose
      working-directory: projects/guessing_game
    # - name: Run tests
    #   run: cargo test --verbose
